### ISSUE TITLE
討論管理介面與帳號

### ISSUE THREAD

**Issue by raindot** [MonospaceTW/goodfood#124]

**Comment by horsekitlin** [comment]
如果是用 database 儲存 User 資料
可以再啟動的時候先檢查一組User 是否存在
不存在就寫入一筆會員資料
他會有一個欄位 admin : true
其他都是 admin : false

但是所有頁面也要檢查哪些是 admin 可以使用登入
哪些不行 也要先確定好再改

**Comment by raindot** [comment]
我們user資料是使用firebase提供的會員系統，我們無法去增加會員系統的欄位，如果要新增欄位，只能另外在firebase資料庫裡新增一個節點儲存會員資料
但如此每次驗證帳號權限時都會增加request
用 database 儲存 User 資料是這個意思嗎？

**Comment by raindot** [comment]
Firebase有提供Admin SDK能夠自定義使用者權限，不過需要裝在伺服器上
https://firebase.google.com/docs/database/admin/start?authuser=0&hl=zh-cn
