### ISSUE TITLE
ignore config file

### ISSUE THREAD

**Issue by kyoyadmoon** [MonospaceTW/goodfood#40]
https://github.com/MonospaceTW/goodfood/blob/master/js/config.js#L3

這個 config 檔案應該要加到 .gitignore 中
可以另外寫一份 config.default.js 設定內容當作設定內容的參考
才不會把敏感資料直接公開在 github 上
p.s. 記得 revoke 目前的 apiKey

**Comment by horsekitlin** [comment]
這部分下個禮拜整理程式碼完成後 
作 firebase 串接的時候會同時改動
