### ISSUE TITLE
測試站時console.log是否要拿掉？

### ISSUE THREAD

**Issue by raindot** [MonospaceTW/goodfood#85]

**Comment by iamcxa** [comment]
我會覺得如果是測試用途的，可以保留；但如果未來是 public 的商業 beta 站那就得拿掉。

不過以 goodfood 來說，我覺得可以保留，才能方便大家快速除錯。

**Comment by horsekitlin** [comment]
這部分我覺得在個人測試完之後養成習慣拿掉console.log

畢竟你們會互相 merge

屆時彼此的 console.log 會互相干擾

到後面也還是要花時間清除或是分辨別人的console.log
